inherit_from: .rubocop_todo.yml

# .rubocop.yml

# rubocop config files for Ruby 2.7 / Rails 6+ project
# blog post: http://joanswork.com/rubocop-rails-getting-started/
# link broken, all I can find: https://github.com/jehughes

AllCops:
  TargetRubyVersion: 2.7
  NewCops: enable

  Include:
    - 'config.ru'
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'
    - 'app/**/*.rb'
    - 'config/**/*.rb'
    - 'lib/**/*.rb'
    - 'spec/**/*.rb'
    - 'db/seeds.rb'

  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'public/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
    - '.git/**/*'
    - 'app/views/**/*'
    - 'Gemfile'
    - 'config/**/*'

Lint/EmptyBlock:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Layout/IndentationConsistency:
  # EnforcedStyle: 'indented_internal_methods'
  EnforcedStyle: normal

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'spec/**/*'

Naming/FileName:
  Exclude:
    - 'Gemfile'
    - 'Guardfile'
    - 'Rakefile'

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
