version: '3'
services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    volumes:
      - ./tmp/downloads:/tmp/downloads

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
    volumes:
      - .:/sample_app
      - ./tmp/downloads:/tmp//downloads
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    stdin_open: true
    tty: true
    command: bundle exec rails server -b 0.0.0.0
volumes:
  mysql-data:
