version: '3'
services:
  db:
    image: mariadb:10.4
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    volumes:
      - ./tmp/downloads:/tmp/downloads

  mailhog:
    image: mailhog/mailhog:v1.0.0
    ports:
      - "8025:8025"

  app: &app
    build: .
    command: ash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0' && bundle exec rails server -b 0.0.0.0"
    environment:
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
    volumes:
      - .:/sample_app
      - ./tmp/downloads:/tmp//downloads
    ports:
      - "3000:3000"
    depends_on:
      - db
      - chrome
    stdin_open: true
    tty: true
  api-mock:
    image: danielgtaylor/apisprout
    profiles:
      - swagger
    ports:
      - 8010:8000
    volumes:
      - ./openapi/merged.yaml:/merged.yaml
    entrypoint: /usr/local/bin/apisprout /merged.yaml --watch
  swagger-ui:
    image: swaggerapi/swagger-ui
    profiles:
      - swagger
    ports:
      - 8011:8080
    volumes:
      - ./openapi/merged.yaml:/usr/share/nginx/html/merged.yaml
    environment:
      API_URL: merged.yaml
  redoc:
    image: redocly/redoc
    profiles:
      - swagger
    ports:
      - 8012:80
    volumes:
      - ./openapi/merged.yaml:/usr/share/nginx/html/merged.yaml
    environment:
      SPEC_URL: merged.yaml
  swaggereditor:
    image: swaggerapi/swagger-editor
    profiles:
      - swagger
    ports:
      - 8013:8080
    volumes:
      - ./openapi/:/usr/share/nginx/htmll
    environment:
      API_URL: merged.yaml
  redoc-cli:
    build: ./docker/redoc-cli
    profiles:
      - swagger
    volumes:
      - ./openapi:/data
  swagger-merger:
    build: ./docker/swagger-merger
    profiles:
      - swagger
    volumes:
      - ./docker/swagger-merger/watch.js:/watch.js
      - ./openapi:/data
    environment:
      NODE_PATH: /usr/local/lib/node_modules
    entrypoint: node /watch

volumes:
  mysql-data:
